#DashboardController
dashboard:
  path: /dashboard
  controller: App\Controller\DashboardController::home
  methods: GET

dashboard_home:
  path: /dashboard/home
  controller: App\Controller\DashboardController::home
  methods: GET

security_controller:
  path: /security
  controller: App\Controller\SecurityController::login
  methods: GET